kind: deployment
spec:
  infrastructure:
    kind: infrastructure
    type: modelDeployment
    spec:
      logGroupId: ocid1.loggroup.oc1.iad..<unique_ID>
      logId: ocid1.log.oc1.iad..<unique_ID>
      projectId: ocid1.datascienceproject.oc1.iad..<unique_ID>
      compartmentId: ocid1.compartment.oc1..<unique_ID>
      shapeName: VM.Standard.E3.Flex
      shapeConfigDetails:
        memoryInGBs: 32
        ocpus: 4
      blockStorageSize: 50
      replica: 1
  runtime:
    kind: runtime
    type: conda
    spec:
      uri:
        name: elasticnet_v1
        destination: oci://bucket@namespace/mlflow-conda-envs/
        gpu: false
        overwrite: false
        keepLocal: true
        localCondaDir: ./conda
